org: wilderemanuel
service: api-alumnos

provider:
  name: aws
  runtime: python3.12
  iam:
    role: aarn:aws:iam::533894290576:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda



